packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@heroui/react": ^3.0.5
  "@hugeicons/core-free-icons": ^4.0.0
  "@hugeicons/react": ^1.1.6
  "@tailwindcss/vite": ^4.3.0
  "@types/node": ^25.5.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  react: ^19.2.6
  react-dom: ^19.2.6
  tailwindcss: ^4.3.0
  typescript: ^6.0.3
  zod: ^4.4.3
  vite-plus: latest
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
blockExoticSubdeps: false
nodeLinker: hoisted
onlyBuiltDependencies:
  - "@heroui-pro/react"
  - "@zowe/secrets-for-zowe-sdk"
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - msw
allowBuilds:
  "@heroui-pro/react": true
  "@zowe/secrets-for-zowe-sdk": true
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  msw: true
minimumReleaseAgeExclude:
  - "@chat-adapter/shared@4.29.0"
  - "@chat-adapter/state-memory@4.29.0"
  - "@chat-adapter/telegram@4.29.0"
  - "@hono/node-server@2.0.3"
  - chat@4.29.0
  - date-fns@4.2.1
  - framer-motion@12.39.0
  - motion-dom@12.39.0
  - motion-utils@12.39.0
  - motion@12.39.0
