packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@hugeicons/core-free-icons": ^4.0.0
  "@hugeicons/react": ^1.1.6
  "@tailwindcss/vite": ^4.2.2
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwindcss: ^4.2.2
  typescript: ^5.9.3
  zod: ^4.3.6
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
