/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSessionIdRouteImport } from './routes/chat.$sessionId'
import { Route as AgentsSessionIdRouteImport } from './routes/agents.$sessionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSessionIdRoute = AgentsSessionIdRouteImport.update({
  id: '/agents/$sessionId',
  path: '/agents/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agents/$sessionId': typeof AgentsSessionIdRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agents/$sessionId': typeof AgentsSessionIdRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agents/$sessionId': typeof AgentsSessionIdRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/agents/$sessionId' | '/chat/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/agents/$sessionId' | '/chat/$sessionId'
  id: '__root__' | '/' | '/settings' | '/agents/$sessionId' | '/chat/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AgentsSessionIdRoute: typeof AgentsSessionIdRoute
  ChatSessionIdRoute: typeof ChatSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$sessionId': {
      id: '/agents/$sessionId'
      path: '/agents/$sessionId'
      fullPath: '/agents/$sessionId'
      preLoaderRoute: typeof AgentsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AgentsSessionIdRoute: AgentsSessionIdRoute,
  ChatSessionIdRoute: ChatSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
